# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Paravion' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SlideMenuControllerSwift'
  pod 'FacebookCore'
  pod 'FacebookLogin'
#  pod 'FacebookShare'

  # Pods for Paravion

  target 'ParavionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ParavionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
